language: generic
services: docker
os: linux

jobs:
  include:
      - os: linux
        arch: arm64-graviton2
        dist: focal
        virt: lxd
        group: edge

install:
    - uname -m
    - echo "hi"

notifications:
  email: false
