env:
    global:
        - REPO_DIR=cffi
        - PLAT=x86_64

language: generic
services: docker
os: linux

jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.6
          - PLAT=aarch64
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.7
          - PLAT=aarch64
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.8
          - PLAT=aarch64
          - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8
          - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}

before_install:
    - sudo apt-get install mercurial
    - hg clone https://foss.heptapod.net/pypy/cffi
    - TEST_DEPENDS="pytest pycparser"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT
after_success:
    - pip install twine
    - twine upload -u mkp2020 ${TRAVIS_BUILD_DIR}/wheelhouse/*
